// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intercom.proto

package com.example.flutterphotometa.protobuf;

public final class FlutterPlugins {
  private FlutterPlugins() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code ValidMethod}
   */
  public enum ValidMethod
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>GET_PHOTO = 1;</code>
     */
    GET_PHOTO(1),
    /**
     * <code>LIST_PHOTOS = 3;</code>
     */
    LIST_PHOTOS(3),
    /**
     * <code>GET_PHOTO_METADATA = 4;</code>
     */
    GET_PHOTO_METADATA(4),
    /**
     * <code>REMOVE_PHOTO_METADATA = 5;</code>
     */
    REMOVE_PHOTO_METADATA(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>GET_PHOTO = 1;</code>
     */
    public static final int GET_PHOTO_VALUE = 1;
    /**
     * <code>LIST_PHOTOS = 3;</code>
     */
    public static final int LIST_PHOTOS_VALUE = 3;
    /**
     * <code>GET_PHOTO_METADATA = 4;</code>
     */
    public static final int GET_PHOTO_METADATA_VALUE = 4;
    /**
     * <code>REMOVE_PHOTO_METADATA = 5;</code>
     */
    public static final int REMOVE_PHOTO_METADATA_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValidMethod valueOf(int value) {
      return forNumber(value);
    }

    public static ValidMethod forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return GET_PHOTO;
        case 3: return LIST_PHOTOS;
        case 4: return GET_PHOTO_METADATA;
        case 5: return REMOVE_PHOTO_METADATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ValidMethod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ValidMethod> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ValidMethod>() {
            @java.lang.Override
            public ValidMethod findValueByNumber(int number) {
              return ValidMethod.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ValidMethodVerifier.INSTANCE;
    }

    private static final class ValidMethodVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ValidMethodVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ValidMethod.forNumber(number) != null;
            }
          };

    private final int value;

    private ValidMethod(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ValidMethod)
  }

  /**
   * Protobuf enum {@code DataType}
   */
  public enum DataType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>NULL = 0;</code>
     */
    NULL(0),
    /**
     * <code>BOOL = 1;</code>
     */
    BOOL(1),
    /**
     * <code>INT32 = 2;</code>
     */
    INT32(2),
    /**
     * <code>INT64 = 3;</code>
     */
    INT64(3),
    /**
     * <code>FLOAT64 = 4;</code>
     */
    FLOAT64(4),
    /**
     * <code>STRING = 5;</code>
     */
    STRING(5),
    /**
     * <code>UINT8LIST = 6;</code>
     */
    UINT8LIST(6),
    /**
     * <code>INT32LIST = 7;</code>
     */
    INT32LIST(7),
    /**
     * <code>INT64LIST = 8;</code>
     */
    INT64LIST(8),
    /**
     * <pre>
     * Dart Does not contain Float32List for buffer writer
     * </pre>
     *
     * <code>FLOAT32LIST = 9;</code>
     */
    FLOAT32LIST(9),
    /**
     * <code>FLOAT64LIST = 10;</code>
     */
    FLOAT64LIST(10),
    /**
     * <code>LIST = 11;</code>
     */
    LIST(11),
    /**
     * <code>MAP = 12;</code>
     */
    MAP(12),
    /**
     * <code>MESSAGE = 13;</code>
     */
    MESSAGE(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NULL = 0;</code>
     */
    public static final int NULL_VALUE = 0;
    /**
     * <code>BOOL = 1;</code>
     */
    public static final int BOOL_VALUE = 1;
    /**
     * <code>INT32 = 2;</code>
     */
    public static final int INT32_VALUE = 2;
    /**
     * <code>INT64 = 3;</code>
     */
    public static final int INT64_VALUE = 3;
    /**
     * <code>FLOAT64 = 4;</code>
     */
    public static final int FLOAT64_VALUE = 4;
    /**
     * <code>STRING = 5;</code>
     */
    public static final int STRING_VALUE = 5;
    /**
     * <code>UINT8LIST = 6;</code>
     */
    public static final int UINT8LIST_VALUE = 6;
    /**
     * <code>INT32LIST = 7;</code>
     */
    public static final int INT32LIST_VALUE = 7;
    /**
     * <code>INT64LIST = 8;</code>
     */
    public static final int INT64LIST_VALUE = 8;
    /**
     * <pre>
     * Dart Does not contain Float32List for buffer writer
     * </pre>
     *
     * <code>FLOAT32LIST = 9;</code>
     */
    public static final int FLOAT32LIST_VALUE = 9;
    /**
     * <code>FLOAT64LIST = 10;</code>
     */
    public static final int FLOAT64LIST_VALUE = 10;
    /**
     * <code>LIST = 11;</code>
     */
    public static final int LIST_VALUE = 11;
    /**
     * <code>MAP = 12;</code>
     */
    public static final int MAP_VALUE = 12;
    /**
     * <code>MESSAGE = 13;</code>
     */
    public static final int MESSAGE_VALUE = 13;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return NULL;
        case 1: return BOOL;
        case 2: return INT32;
        case 3: return INT64;
        case 4: return FLOAT64;
        case 5: return STRING;
        case 6: return UINT8LIST;
        case 7: return INT32LIST;
        case 8: return INT64LIST;
        case 9: return FLOAT32LIST;
        case 10: return FLOAT64LIST;
        case 11: return LIST;
        case 12: return MAP;
        case 13: return MESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            @java.lang.Override
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return DataTypeVerifier.INSTANCE;
    }

    private static final class DataTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new DataTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return DataType.forNumber(number) != null;
            }
          };

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DataType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
