// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: photo.proto

package com.example.flutterphotometa.protobuf;

public final class PhotoApis {
  private PhotoApis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PhotoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Photo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * photo size in pixel
     * </pre>
     *
     * <code>int32 width = 2;</code>
     */
    int getWidth();

    /**
     * <code>int32 height = 3;</code>
     */
    int getHeight();

    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    java.lang.String getLocalIdentifier();
    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    com.google.protobuf.ByteString
        getLocalIdentifierBytes();

    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    long getFileSize();
  }
  /**
   * <pre>
   * Photo data information
   * </pre>
   *
   * Protobuf type {@code Photo}
   */
  public  static final class Photo extends
      com.google.protobuf.GeneratedMessageLite<
          Photo, Photo.Builder> implements
      // @@protoc_insertion_point(message_implements:Photo)
      PhotoOrBuilder {
    private Photo() {
      name_ = "";
      localIdentifier_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <pre>
     * name of file represent the photo
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <pre>
     * photo size in pixel
     * </pre>
     *
     * <code>int32 width = 2;</code>
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }
    /**
     * <pre>
     * photo size in pixel
     * </pre>
     *
     * <code>int32 width = 2;</code>
     */
    private void setWidth(int value) {
      
      width_ = value;
    }
    /**
     * <pre>
     * photo size in pixel
     * </pre>
     *
     * <code>int32 width = 2;</code>
     */
    private void clearWidth() {
      
      width_ = 0;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>int32 height = 3;</code>
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }
    /**
     * <code>int32 height = 3;</code>
     */
    private void setHeight(int value) {
      
      height_ = value;
    }
    /**
     * <code>int32 height = 3;</code>
     */
    private void clearHeight() {
      
      height_ = 0;
    }

    public static final int LOCALIDENTIFIER_FIELD_NUMBER = 4;
    private java.lang.String localIdentifier_;
    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getLocalIdentifier() {
      return localIdentifier_;
    }
    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocalIdentifierBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(localIdentifier_);
    }
    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    private void setLocalIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      localIdentifier_ = value;
    }
    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    private void clearLocalIdentifier() {
      
      localIdentifier_ = getDefaultInstance().getLocalIdentifier();
    }
    /**
     * <pre>
     * photo path (Android) or id (iOS) depend on platform specific
     * </pre>
     *
     * <code>string localIdentifier = 4;</code>
     */
    private void setLocalIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      localIdentifier_ = value.toStringUtf8();
    }

    public static final int FILESIZE_FIELD_NUMBER = 5;
    private long fileSize_;
    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }
    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    private void setFileSize(long value) {
      
      fileSize_ = value;
    }
    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    private void clearFileSize() {
      
      fileSize_ = 0L;
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.flutterphotometa.protobuf.PhotoApis.Photo prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Photo data information
     * </pre>
     *
     * Protobuf type {@code Photo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.flutterphotometa.protobuf.PhotoApis.Photo, Builder> implements
        // @@protoc_insertion_point(builder_implements:Photo)
        com.example.flutterphotometa.protobuf.PhotoApis.PhotoOrBuilder {
      // Construct using com.example.flutterphotometa.protobuf.PhotoApis.Photo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * name of file represent the photo
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <pre>
       * name of file represent the photo
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <pre>
       * name of file represent the photo
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <pre>
       * name of file represent the photo
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <pre>
       * name of file represent the photo
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * photo size in pixel
       * </pre>
       *
       * <code>int32 width = 2;</code>
       */
      @java.lang.Override
      public int getWidth() {
        return instance.getWidth();
      }
      /**
       * <pre>
       * photo size in pixel
       * </pre>
       *
       * <code>int32 width = 2;</code>
       */
      public Builder setWidth(int value) {
        copyOnWrite();
        instance.setWidth(value);
        return this;
      }
      /**
       * <pre>
       * photo size in pixel
       * </pre>
       *
       * <code>int32 width = 2;</code>
       */
      public Builder clearWidth() {
        copyOnWrite();
        instance.clearWidth();
        return this;
      }

      /**
       * <code>int32 height = 3;</code>
       */
      @java.lang.Override
      public int getHeight() {
        return instance.getHeight();
      }
      /**
       * <code>int32 height = 3;</code>
       */
      public Builder setHeight(int value) {
        copyOnWrite();
        instance.setHeight(value);
        return this;
      }
      /**
       * <code>int32 height = 3;</code>
       */
      public Builder clearHeight() {
        copyOnWrite();
        instance.clearHeight();
        return this;
      }

      /**
       * <pre>
       * photo path (Android) or id (iOS) depend on platform specific
       * </pre>
       *
       * <code>string localIdentifier = 4;</code>
       */
      @java.lang.Override
      public java.lang.String getLocalIdentifier() {
        return instance.getLocalIdentifier();
      }
      /**
       * <pre>
       * photo path (Android) or id (iOS) depend on platform specific
       * </pre>
       *
       * <code>string localIdentifier = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLocalIdentifierBytes() {
        return instance.getLocalIdentifierBytes();
      }
      /**
       * <pre>
       * photo path (Android) or id (iOS) depend on platform specific
       * </pre>
       *
       * <code>string localIdentifier = 4;</code>
       */
      public Builder setLocalIdentifier(
          java.lang.String value) {
        copyOnWrite();
        instance.setLocalIdentifier(value);
        return this;
      }
      /**
       * <pre>
       * photo path (Android) or id (iOS) depend on platform specific
       * </pre>
       *
       * <code>string localIdentifier = 4;</code>
       */
      public Builder clearLocalIdentifier() {
        copyOnWrite();
        instance.clearLocalIdentifier();
        return this;
      }
      /**
       * <pre>
       * photo path (Android) or id (iOS) depend on platform specific
       * </pre>
       *
       * <code>string localIdentifier = 4;</code>
       */
      public Builder setLocalIdentifierBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocalIdentifierBytes(value);
        return this;
      }

      /**
       * <pre>
       * photo file size in bytes
       * </pre>
       *
       * <code>int64 fileSize = 5;</code>
       */
      @java.lang.Override
      public long getFileSize() {
        return instance.getFileSize();
      }
      /**
       * <pre>
       * photo file size in bytes
       * </pre>
       *
       * <code>int64 fileSize = 5;</code>
       */
      public Builder setFileSize(long value) {
        copyOnWrite();
        instance.setFileSize(value);
        return this;
      }
      /**
       * <pre>
       * photo file size in bytes
       * </pre>
       *
       * <code>int64 fileSize = 5;</code>
       */
      public Builder clearFileSize() {
        copyOnWrite();
        instance.clearFileSize();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Photo)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.flutterphotometa.protobuf.PhotoApis.Photo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
              "width_",
              "height_",
              "localIdentifier_",
              "fileSize_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0004\u0004\u0208\u0005\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.flutterphotometa.protobuf.PhotoApis.Photo> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.flutterphotometa.protobuf.PhotoApis.Photo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.flutterphotometa.protobuf.PhotoApis.Photo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Photo)
    private static final com.example.flutterphotometa.protobuf.PhotoApis.Photo DEFAULT_INSTANCE;
    static {
      Photo defaultInstance = new Photo();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Photo.class, defaultInstance);
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.Photo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Photo> PARSER;

    public static com.google.protobuf.Parser<Photo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PhotosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Photos)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    java.util.List<com.example.flutterphotometa.protobuf.PhotoApis.Photo> 
        getPhotosList();
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    com.example.flutterphotometa.protobuf.PhotoApis.Photo getPhotos(int index);
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    int getPhotosCount();
  }
  /**
   * <pre>
   * All photo list
   * </pre>
   *
   * Protobuf type {@code Photos}
   */
  public  static final class Photos extends
      com.google.protobuf.GeneratedMessageLite<
          Photos, Photos.Builder> implements
      // @@protoc_insertion_point(message_implements:Photos)
      PhotosOrBuilder {
    private Photos() {
      photos_ = emptyProtobufList();
    }
    public static final int PHOTOS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.example.flutterphotometa.protobuf.PhotoApis.Photo> photos_;
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.flutterphotometa.protobuf.PhotoApis.Photo> getPhotosList() {
      return photos_;
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    public java.util.List<? extends com.example.flutterphotometa.protobuf.PhotoApis.PhotoOrBuilder> 
        getPhotosOrBuilderList() {
      return photos_;
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    @java.lang.Override
    public int getPhotosCount() {
      return photos_.size();
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    @java.lang.Override
    public com.example.flutterphotometa.protobuf.PhotoApis.Photo getPhotos(int index) {
      return photos_.get(index);
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    public com.example.flutterphotometa.protobuf.PhotoApis.PhotoOrBuilder getPhotosOrBuilder(
        int index) {
      return photos_.get(index);
    }
    private void ensurePhotosIsMutable() {
      if (!photos_.isModifiable()) {
        photos_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(photos_);
       }
    }

    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void setPhotos(
        int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhotosIsMutable();
      photos_.set(index, value);
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void setPhotos(
        int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo.Builder builderForValue) {
      ensurePhotosIsMutable();
      photos_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void addPhotos(com.example.flutterphotometa.protobuf.PhotoApis.Photo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhotosIsMutable();
      photos_.add(value);
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void addPhotos(
        int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhotosIsMutable();
      photos_.add(index, value);
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void addPhotos(
        com.example.flutterphotometa.protobuf.PhotoApis.Photo.Builder builderForValue) {
      ensurePhotosIsMutable();
      photos_.add(builderForValue.build());
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void addPhotos(
        int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo.Builder builderForValue) {
      ensurePhotosIsMutable();
      photos_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void addAllPhotos(
        java.lang.Iterable<? extends com.example.flutterphotometa.protobuf.PhotoApis.Photo> values) {
      ensurePhotosIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, photos_);
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void clearPhotos() {
      photos_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Photo photos = 1;</code>
     */
    private void removePhotos(int index) {
      ensurePhotosIsMutable();
      photos_.remove(index);
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.flutterphotometa.protobuf.PhotoApis.Photos prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * All photo list
     * </pre>
     *
     * Protobuf type {@code Photos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.flutterphotometa.protobuf.PhotoApis.Photos, Builder> implements
        // @@protoc_insertion_point(builder_implements:Photos)
        com.example.flutterphotometa.protobuf.PhotoApis.PhotosOrBuilder {
      // Construct using com.example.flutterphotometa.protobuf.PhotoApis.Photos.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.flutterphotometa.protobuf.PhotoApis.Photo> getPhotosList() {
        return java.util.Collections.unmodifiableList(
            instance.getPhotosList());
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      @java.lang.Override
      public int getPhotosCount() {
        return instance.getPhotosCount();
      }/**
       * <code>repeated .Photo photos = 1;</code>
       */
      @java.lang.Override
      public com.example.flutterphotometa.protobuf.PhotoApis.Photo getPhotos(int index) {
        return instance.getPhotos(index);
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder setPhotos(
          int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo value) {
        copyOnWrite();
        instance.setPhotos(index, value);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder setPhotos(
          int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo.Builder builderForValue) {
        copyOnWrite();
        instance.setPhotos(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder addPhotos(com.example.flutterphotometa.protobuf.PhotoApis.Photo value) {
        copyOnWrite();
        instance.addPhotos(value);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder addPhotos(
          int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo value) {
        copyOnWrite();
        instance.addPhotos(index, value);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder addPhotos(
          com.example.flutterphotometa.protobuf.PhotoApis.Photo.Builder builderForValue) {
        copyOnWrite();
        instance.addPhotos(builderForValue);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder addPhotos(
          int index, com.example.flutterphotometa.protobuf.PhotoApis.Photo.Builder builderForValue) {
        copyOnWrite();
        instance.addPhotos(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder addAllPhotos(
          java.lang.Iterable<? extends com.example.flutterphotometa.protobuf.PhotoApis.Photo> values) {
        copyOnWrite();
        instance.addAllPhotos(values);
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder clearPhotos() {
        copyOnWrite();
        instance.clearPhotos();
        return this;
      }
      /**
       * <code>repeated .Photo photos = 1;</code>
       */
      public Builder removePhotos(int index) {
        copyOnWrite();
        instance.removePhotos(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Photos)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.flutterphotometa.protobuf.PhotoApis.Photos();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "photos_",
              com.example.flutterphotometa.protobuf.PhotoApis.Photo.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.flutterphotometa.protobuf.PhotoApis.Photos> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.flutterphotometa.protobuf.PhotoApis.Photos.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.flutterphotometa.protobuf.PhotoApis.Photos>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Photos)
    private static final com.example.flutterphotometa.protobuf.PhotoApis.Photos DEFAULT_INSTANCE;
    static {
      Photos defaultInstance = new Photos();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Photos.class, defaultInstance);
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.Photos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Photos> PARSER;

    public static com.google.protobuf.Parser<Photos> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Location)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * <pre>
   * Geograpical location
   * </pre>
   *
   * Protobuf type {@code Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageLite<
          Location, Location.Builder> implements
      // @@protoc_insertion_point(message_implements:Location)
      LocationOrBuilder {
    private Location() {
    }
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>double latitude = 1;</code>
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>double latitude = 1;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>double longitude = 2;</code>
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>double longitude = 2;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.flutterphotometa.protobuf.PhotoApis.Location prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Geograpical location
     * </pre>
     *
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.flutterphotometa.protobuf.PhotoApis.Location, Builder> implements
        // @@protoc_insertion_point(builder_implements:Location)
        com.example.flutterphotometa.protobuf.PhotoApis.LocationOrBuilder {
      // Construct using com.example.flutterphotometa.protobuf.PhotoApis.Location.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>double latitude = 1;</code>
       */
      @java.lang.Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>double longitude = 2;</code>
       */
      @java.lang.Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Location)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.flutterphotometa.protobuf.PhotoApis.Location();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "latitude_",
              "longitude_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.flutterphotometa.protobuf.PhotoApis.Location> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.flutterphotometa.protobuf.PhotoApis.Location.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.flutterphotometa.protobuf.PhotoApis.Location>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Location)
    private static final com.example.flutterphotometa.protobuf.PhotoApis.Location DEFAULT_INSTANCE;
    static {
      Location defaultInstance = new Location();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Location.class, defaultInstance);
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Location> PARSER;

    public static com.google.protobuf.Parser<Location> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PhotoMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PhotoMetadata)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * date and time when photo is taken
     * </pre>
     *
     * <code>int64 captureAt = 1;</code>
     */
    long getCaptureAt();

    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    boolean hasLocation();
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    com.example.flutterphotometa.protobuf.PhotoApis.Location getLocation();

    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    java.lang.String getMake();
    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    com.google.protobuf.ByteString
        getMakeBytes();

    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    long getFileSize();
  }
  /**
   * <pre>
   * Photo Metadata content sensitive information
   * </pre>
   *
   * Protobuf type {@code PhotoMetadata}
   */
  public  static final class PhotoMetadata extends
      com.google.protobuf.GeneratedMessageLite<
          PhotoMetadata, PhotoMetadata.Builder> implements
      // @@protoc_insertion_point(message_implements:PhotoMetadata)
      PhotoMetadataOrBuilder {
    private PhotoMetadata() {
      make_ = "";
    }
    public static final int CAPTUREAT_FIELD_NUMBER = 1;
    private long captureAt_;
    /**
     * <pre>
     * date and time when photo is taken
     * </pre>
     *
     * <code>int64 captureAt = 1;</code>
     */
    @java.lang.Override
    public long getCaptureAt() {
      return captureAt_;
    }
    /**
     * <pre>
     * date and time when photo is taken
     * </pre>
     *
     * <code>int64 captureAt = 1;</code>
     */
    private void setCaptureAt(long value) {
      
      captureAt_ = value;
    }
    /**
     * <pre>
     * date and time when photo is taken
     * </pre>
     *
     * <code>int64 captureAt = 1;</code>
     */
    private void clearCaptureAt() {
      
      captureAt_ = 0L;
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private com.example.flutterphotometa.protobuf.PhotoApis.Location location_;
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    @java.lang.Override
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    @java.lang.Override
    public com.example.flutterphotometa.protobuf.PhotoApis.Location getLocation() {
      return location_ == null ? com.example.flutterphotometa.protobuf.PhotoApis.Location.getDefaultInstance() : location_;
    }
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    private void setLocation(com.example.flutterphotometa.protobuf.PhotoApis.Location value) {
      if (value == null) {
        throw new NullPointerException();
      }
      location_ = value;
      
      }
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    private void setLocation(
        com.example.flutterphotometa.protobuf.PhotoApis.Location.Builder builderForValue) {
      location_ = builderForValue.build();
      
    }
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeLocation(com.example.flutterphotometa.protobuf.PhotoApis.Location value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (location_ != null &&
          location_ != com.example.flutterphotometa.protobuf.PhotoApis.Location.getDefaultInstance()) {
        location_ =
          com.example.flutterphotometa.protobuf.PhotoApis.Location.newBuilder(location_).mergeFrom(value).buildPartial();
      } else {
        location_ = value;
      }
      
    }
    /**
     * <pre>
     * a geographical location where photo is taken
     * </pre>
     *
     * <code>.Location location = 2;</code>
     */
    private void clearLocation() {  location_ = null;
      
    }

    public static final int MAKE_FIELD_NUMBER = 3;
    private java.lang.String make_;
    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getMake() {
      return make_;
    }
    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMakeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(make_);
    }
    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    private void setMake(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      make_ = value;
    }
    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    private void clearMake() {
      
      make_ = getDefaultInstance().getMake();
    }
    /**
     * <pre>
     * a company who produce the camera
     * </pre>
     *
     * <code>string make = 3;</code>
     */
    private void setMakeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      make_ = value.toStringUtf8();
    }

    public static final int FILESIZE_FIELD_NUMBER = 5;
    private long fileSize_;
    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }
    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    private void setFileSize(long value) {
      
      fileSize_ = value;
    }
    /**
     * <pre>
     * photo file size in bytes
     * </pre>
     *
     * <code>int64 fileSize = 5;</code>
     */
    private void clearFileSize() {
      
      fileSize_ = 0L;
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Photo Metadata content sensitive information
     * </pre>
     *
     * Protobuf type {@code PhotoMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata, Builder> implements
        // @@protoc_insertion_point(builder_implements:PhotoMetadata)
        com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadataOrBuilder {
      // Construct using com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * date and time when photo is taken
       * </pre>
       *
       * <code>int64 captureAt = 1;</code>
       */
      @java.lang.Override
      public long getCaptureAt() {
        return instance.getCaptureAt();
      }
      /**
       * <pre>
       * date and time when photo is taken
       * </pre>
       *
       * <code>int64 captureAt = 1;</code>
       */
      public Builder setCaptureAt(long value) {
        copyOnWrite();
        instance.setCaptureAt(value);
        return this;
      }
      /**
       * <pre>
       * date and time when photo is taken
       * </pre>
       *
       * <code>int64 captureAt = 1;</code>
       */
      public Builder clearCaptureAt() {
        copyOnWrite();
        instance.clearCaptureAt();
        return this;
      }

      /**
       * <pre>
       * a geographical location where photo is taken
       * </pre>
       *
       * <code>.Location location = 2;</code>
       */
      @java.lang.Override
      public boolean hasLocation() {
        return instance.hasLocation();
      }
      /**
       * <pre>
       * a geographical location where photo is taken
       * </pre>
       *
       * <code>.Location location = 2;</code>
       */
      @java.lang.Override
      public com.example.flutterphotometa.protobuf.PhotoApis.Location getLocation() {
        return instance.getLocation();
      }
      /**
       * <pre>
       * a geographical location where photo is taken
       * </pre>
       *
       * <code>.Location location = 2;</code>
       */
      public Builder setLocation(com.example.flutterphotometa.protobuf.PhotoApis.Location value) {
        copyOnWrite();
        instance.setLocation(value);
        return this;
        }
      /**
       * <pre>
       * a geographical location where photo is taken
       * </pre>
       *
       * <code>.Location location = 2;</code>
       */
      public Builder setLocation(
          com.example.flutterphotometa.protobuf.PhotoApis.Location.Builder builderForValue) {
        copyOnWrite();
        instance.setLocation(builderForValue);
        return this;
      }
      /**
       * <pre>
       * a geographical location where photo is taken
       * </pre>
       *
       * <code>.Location location = 2;</code>
       */
      public Builder mergeLocation(com.example.flutterphotometa.protobuf.PhotoApis.Location value) {
        copyOnWrite();
        instance.mergeLocation(value);
        return this;
      }
      /**
       * <pre>
       * a geographical location where photo is taken
       * </pre>
       *
       * <code>.Location location = 2;</code>
       */
      public Builder clearLocation() {  copyOnWrite();
        instance.clearLocation();
        return this;
      }

      /**
       * <pre>
       * a company who produce the camera
       * </pre>
       *
       * <code>string make = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getMake() {
        return instance.getMake();
      }
      /**
       * <pre>
       * a company who produce the camera
       * </pre>
       *
       * <code>string make = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMakeBytes() {
        return instance.getMakeBytes();
      }
      /**
       * <pre>
       * a company who produce the camera
       * </pre>
       *
       * <code>string make = 3;</code>
       */
      public Builder setMake(
          java.lang.String value) {
        copyOnWrite();
        instance.setMake(value);
        return this;
      }
      /**
       * <pre>
       * a company who produce the camera
       * </pre>
       *
       * <code>string make = 3;</code>
       */
      public Builder clearMake() {
        copyOnWrite();
        instance.clearMake();
        return this;
      }
      /**
       * <pre>
       * a company who produce the camera
       * </pre>
       *
       * <code>string make = 3;</code>
       */
      public Builder setMakeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMakeBytes(value);
        return this;
      }

      /**
       * <pre>
       * photo file size in bytes
       * </pre>
       *
       * <code>int64 fileSize = 5;</code>
       */
      @java.lang.Override
      public long getFileSize() {
        return instance.getFileSize();
      }
      /**
       * <pre>
       * photo file size in bytes
       * </pre>
       *
       * <code>int64 fileSize = 5;</code>
       */
      public Builder setFileSize(long value) {
        copyOnWrite();
        instance.setFileSize(value);
        return this;
      }
      /**
       * <pre>
       * photo file size in bytes
       * </pre>
       *
       * <code>int64 fileSize = 5;</code>
       */
      public Builder clearFileSize() {
        copyOnWrite();
        instance.clearFileSize();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PhotoMetadata)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "captureAt_",
              "location_",
              "make_",
              "fileSize_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0005\u0004\u0000\u0000\u0000\u0001\u0002\u0002\t" +
                "\u0003\u0208\u0005\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:PhotoMetadata)
    private static final com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata DEFAULT_INSTANCE;
    static {
      PhotoMetadata defaultInstance = new PhotoMetadata();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PhotoMetadata.class, defaultInstance);
    }

    public static com.example.flutterphotometa.protobuf.PhotoApis.PhotoMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PhotoMetadata> PARSER;

    public static com.google.protobuf.Parser<PhotoMetadata> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
